# Generated by Django 3.2.5 on 2021-07-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20210715_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='viiii',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
