# Generated by Django 3.2.5 on 2021-07-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_topic_viiii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='viiii',
        ),
    ]
