# Generated by Django 3.2.5 on 2021-07-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_remove_topic_viiii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='last_updated',
        ),
    ]
